### ISSUE TITLE
d-star-lite.exe "Simulator 1" "../maps/map-03-real.bmp" "../maps/map-03-robot.bmp" 0 0 120 249 30

### ISSUE THREAD

**Issue by yaoqingyuan** [azampagl/robotics-d-star-lite#1]
drop-dead halt

**Comment by RiyaUplenchwar** [comment]
How we can implement D*Lite algorithm by using the google maps API..

**Comment by azampagl** [comment]
Sorry guys, I haven't maintained this repo for a while. I'm not sure it even still runs (built over 6 years ago)!
